### ISSUE TITLE
Support Dalamud API 5

### ISSUE THREAD

**Issue by noproxy** [Karlin-Z/DalamudPlugins#10]
国际服目前已经是API 5, 国服3月更新后卫月也会升级到API 5, 希望作者能抽空兼容API 5. 

非常感谢.

以下问题与此issue相同:
#9 
#6

**Comment by zelkova91** [comment]
同上，希望大神能升级插件至API 5。我是玩国际服的，6.1推出的pvp改革非常让人上瘾，而且节奏非常的快，期待能使用这插件。

感谢！

**Comment by Karlin-Z** [comment]
api5无需适配，国际服由于我没有账号和客户端，抱歉无法适配，可参考源码自行编译适配版本[https://github.com/Karlin-Z/PvPSelector](url)
