### ISSUE TITLE
PvPSelector可以加上不选中特定职业的选项吗

### ISSUE THREAD

**Issue by zxwqwq** [Karlin-Z/DalamudPlugins#15]
比如我想设置默认不选择【暗黑骑士】为目标，这个功能可以实现吗？

**Comment by evridiki778** [comment]
我真的希望看到某种类型的buff过滤器。我不知道这是否可行。
黑暗骑士是最糟糕的，因为它能降到1HP，所以PvPSelector坚持使用它。

黑暗骑士 > 跳过[Living Dead] (Buff ID: 3039)
圣骑士 > 跳过[Hallowed Ground] (Buff ID: 1302)
武士 > 跳过[Chiten] (Buff ID: 1240)
所有人 > 跳过[Guard] (Buff ID: 3054)

谢谢你，为我糟糕的中文感到抱歉。

**Comment by Karlin-Z** [comment]
Hello guys, happy new year. PvPSelector has been updated to 2.x to adapt for 6.3 worldwide/6.2CN. The above functions can all be customized.
Please use main branch for CN game and Global branch for worldwide game.
Thanks for your patience.
