### ISSUE TITLE
PvPSelector for 6.3 / NET 7 / API 8

### ISSUE THREAD

**Issue by evridiki778** [Karlin-Z/DalamudPlugins#17]
Hello, thank you for making PvPSelector, it's a fantastic addon.

International FFXIV was recently updated to 6.3 and PvPSelector sadly no longer works. The [Api4 version](https://github.com/Karlin-Z/DalamudPlugins/tree/Api4) worked until API 7 (6.2), but now it completely crashes the game.

Would it be possible to adapt PvPSelector for API 8? If not, could you make [the Api4 version](https://github.com/Karlin-Z/DalamudPlugins/tree/Api4) source code public?

Thank you very much.

**Comment by Karlin-Z** [comment]
Thank you for your support and trust.
I plan to update PvPSelector and add some new features after the Chinese New Year, please be patient.

**Comment by Karlin-Z** [comment]
Hello guys, happy new year. PvPSelector has been updated to 2.x to adapt for 6.3 worldwide/6.2CN.
Please use main branch for CN game and Global branch for worldwide game.
Thanks for your patience.
