### ISSUE TITLE
CN version only?

### ISSUE THREAD

**Issue by Nullsloth** [Karlin-Z/DalamudPlugins#2]
Are these plugins for CN version only? When I try to install PvP Selector it crashes game. If it is enabled they wont allow game to launch.

**Comment by Karlin-Z** [comment]
yep.It only build for CN client.If you want help to suport for international client.Please contact me.

**Comment by Nullsloth** [comment]
> yep.It only build for CN client.If you want help to suport for international client.Please contact me.

Sure I would love to try and help.

**Comment by haojunsui** [comment]
Hi Karlin, not sure if @Nullsloth already built it for INTL client. If not, I would like to help build it for INTL client.
