### ISSUE TITLE
CN server pvpselector does not work

### ISSUE THREAD

**Issue by ZYZ-CN** [Karlin-Z/DalamudPlugins#6]
![image](https://user-images.githubusercontent.com/62315797/138545844-904faba9-6c61-424f-8c46-90e72b38d35e.png)
I downloaded from your latest version PVPseletor, but it does not seem to work in DevPlugins folder. 
When I tried to type your URL in , although it has been conneted, there is still no your plugins in Dalamud plugins to load.
![image](https://user-images.githubusercontent.com/62315797/138545944-558a0913-fb02-4df6-a5c3-98d8e1322e00.png)

**Comment by takaqiao** [comment]
> > 英 语 交 流 大 会
> 
> 干嘛，不准说英语是吧，歧视是吧。

哈哈哈哈哈
