### ISSUE TITLE
5.57更新之后 Ninjutsu Assist导致游戏崩溃

### ISSUE THREAD

**Issue by 4679** [Karlin-Z/DalamudPlugins#7]
使用忍术的时候游戏会崩溃
[dalamud_appcrash.dmp.gz](https://github.com/Karlin-Z/DalamudPlugins/files/7511211/dalamud_appcrash.dmp.gz)
[dalamud_appcrash.log](https://github.com/Karlin-Z/DalamudPlugins/files/7511213/dalamud_appcrash.log)
log和dump已上传

**Comment by Karlin-Z** [comment]
不用看log我都知道会崩溃，等我回家更新
